// src/templates.ts

export type Template = {
    id: string;
    name: string;
    description: string;
    goal: string;
    pillars: string[];
    tasks: string[][];
  };
  
  // helper to ensure 8×8 tasks
  const makeTasks = (pillars: string[][]): string[][] => {
    return Array.from({ length: 8 }, (_, p) =>
      Array.from({ length: 8 }, (_, t) => pillars[p]?.[t] ?? "")
    );
  };
  
  export const TEMPLATES: Template[] = [
    {
      id: "marathon",
      name: "Run a Marathon",
      description: "Build base, stay healthy, and finish 42.2 km strong.",
      goal: "Run a full marathon by [date]",
      pillars: [
        "Training Base",
        "Strength & Mobility",
        "Recovery & Sleep",
        "Nutrition & Hydration",
        "Mindset & Motivation",
        "Logistics & Gear",
        "Coaching & Feedback",
        "Life Balance",
      ],
      tasks: makeTasks([
        [
          "Follow a beginner plan 3–4 runs per week",
          "Schedule 1 weekly long run on the same day",
          "Warm up 5–10 minutes before every run",
          "Cool down + light stretching after runs",
          "Track every run in an app or notebook",
          "Increase weekly distance by max 10%",
          "Include at least 1 very easy run weekly",
          "Plan a cut-back week every 4th week",
        ],
        [
          "Do 2 short strength sessions per week",
          "Focus on glutes, hamstrings, and core",
          "5–10 minutes of mobility after easy runs",
          "Foam roll legs 2–3x per week",
          "Add single-leg balance work weekly",
          "Include calf strengthening 2x per week",
          "Check running form once a week (video)",
          "Book physio if pain lasts more than 3 days",
        ],
        [
          "Aim for 7–9 hours of sleep per night",
          "Set consistent bedtime and wake time",
          "No screens 30 minutes before bed",
          "Post-long-run nap or quiet rest",
          "Hydrate in the evening before long runs",
          "Schedule at least 1 full rest day weekly",
          "Lower training if stress or illness spikes",
          "Do 5 minutes of breathing before sleep",
        ],
        [
          "Drink water with every meal",
          "Bring a bottle on every run over 30 mins",
          "Practice race-day fueling once weekly",
          "Eat a carb-focused meal before long runs",
          "Include protein in every meal",
          "Limit heavy new foods before big runs",
          "Track how foods feel during long efforts",
          "Prepare simple post-run snack in advance",
        ],
        [
          "Write down why this goal matters",
          "Visualize crossing the finish line daily",
          "Celebrate every long-run completed",
          "Reframe bad runs as data, not failure",
          "Run with music or podcasts you enjoy",
          "Run with a friend once a week if possible",
          "Review progress every Sunday night",
          "Prepare a mantra for tough moments",
        ],
        [
          "Pick a specific race and register",
          "Map safe and convenient running routes",
          "Lay out clothes the night before runs",
          "Choose 1–2 pairs of good running shoes",
          "Keep a small running kit bag ready",
          "Plan transport for race-day now",
          "Check weather the night before long runs",
          "Charge watch/phone before training days",
        ],
        [
          "Ask an experienced friend for tips",
          "Check in with a coach or plan weekly",
          "Log how each run felt from 1–10",
          "Adjust plan based on fatigue trends",
          "Share weekly recap with someone you trust",
          "Ask for support in busy weeks",
          "Review what worked last week, every week",
          "Update plan once a month as you improve",
        ],
        [
          "Block out time for training in calendar",
          "Discuss schedule with family/partner",
          "Protect 1 non-running fun activity weekly",
          "Plan backup indoor options for bad weather",
          "Prep meals for busy training days",
          "Keep work meetings away from long-run day",
          "Say no to one non-essential commitment",
          "Plan post-race celebration or reward",
        ],
      ]),
    },
    {
      id: "book",
      name: "Write a Book",
      description: "From idea to finished first draft and revision.",
      goal: "Complete a full first draft by [date].",
      pillars: [
        "Writing Habit",
        "Outline & Structure",
        "Research",
        "Drafting",
        "Revision",
        "Publishing Plan",
        "Platform & Audience",
        "Environment & Time",
      ],
      tasks: makeTasks([
        [
          "Write at a set time 5 days per week",
          "Set a small daily word goal (e.g., 300)",
          "Use a simple timer (25 minutes on, 5 off)",
          "Track daily streak on paper or app",
          "Turn off notifications while writing",
          "Start each session with 3 deep breaths",
          "End sessions by noting tomorrow’s task",
          "Reward yourself after 5 writing days",
        ],
        [
          "Brainstorm key themes and messages",
          "List all potential chapters on one page",
          "Arrange chapters into a rough order",
          "Identify beginning, middle, and ending",
          "Add 3–5 bullet points per chapter",
          "Check that the outline matches your theme",
          "Revise outline after finishing 25% of draft",
          "Lock outline once you hit 50% of draft",
        ],
        [
          "List gaps where you need more info",
          "Collect 3–5 core sources for your topic",
          "Keep research notes in one place",
          "Highlight only what supports your thesis",
          "Avoid research during writing sprints",
          "Schedule separate research sessions",
          "Summarize insights in your own words",
          "Set a limit for research time per week",
        ],
        [
          "Draft one chapter at a time",
          "Write first, edit later (no backspacing)",
          "Use placeholders instead of pausing research",
          "Aim for ugly first drafts, not perfect ones",
          "Track word count per session",
          "Note which chapters feel hardest",
          "Finish a full draft before major rewrites",
          "Take a 3–7 day break after finishing draft",
        ],
        [
          "Do a first pass for big structural issues",
          "Check each chapter for a clear purpose",
          "Highlight or cut weak scenes/sections",
          "Tighten long paragraphs or repeat ideas",
          "Read key pages aloud for clarity",
          "Ask 1–2 trusted readers for feedback",
          "Create a revision checklist from feedback",
          "Schedule a final polish pass at the end",
        ],
        [
          "Decide between self-pub and traditional",
          "Research 3 comparable books in your niche",
          "Make a rough launch timeline",
          "List possible agents or publishers (if any)",
          "Draft a short book description (blurb)",
          "Collect testimonials or beta reader quotes",
          "Plan basic launch steps on a single page",
          "Set a realistic launch window, not a day",
        ],
        [
          "Choose 1 primary platform (email, IG, etc.)",
          "Post about the journey 1–2x per week",
          "Collect email addresses in a simple list",
          "Share small excerpts or ideas regularly",
          "Note which posts people respond to most",
          "Ask audience one question about the topic",
          "Invite 5–10 people to be beta readers",
          "Thank and credit supporters by name",
        ],
        [
          "Choose 1 main writing location",
          "Keep writing tools ready in one spot",
          "Schedule writing when you have most energy",
          "Protect that time as a meeting with yourself",
          "Have a simple pre-writing ritual",
          "Use noise-cancelling or ambient sounds",
          "Track which times of day work best",
          "Review your weekly schedule every Sunday",
        ],
      ]),
    },
    {
      id: "career",
      name: "Career Change",
      description: "Shift into a new role or field with a clear plan.",
      goal: "Transition into a new role/field I enjoy and can grow in by [date].",
      pillars: [
        "Clarity & Direction",
        "Skills & Training",
        "Portfolio & Proof",
        "Networking",
        "Applications & Outreach",
        "Financial Cushion",
        "Mindset & Identity",
        "Life Logistics",
      ],
      tasks: makeTasks([
        [
          "List reasons you want to change careers",
          "Identify 3 target roles or fields",
          "Write a one-sentence career direction",
          "List your top 5 transferable skills",
          "Research day-in-the-life for target roles",
          "Note non-negotiables (salary, location, hours)",
          "Write a short ‘future resume’ for yourself",
          "Revisit direction every month and tweak",
        ],
        [
          "Identify 2–3 key skills missing today",
          "Pick 1 course or resource for each skill",
          "Study 20–30 minutes most days",
          "Apply new skills in tiny practice projects",
          "Save notes from all practice work",
          "Ask someone to review your skill progress",
          "Track skills gained in a simple list",
          "Update LinkedIn/Resume as skills grow",
        ],
        [
          "Choose 1–2 portfolio formats (site, PDF, etc.)",
          "Collect old work that shows your abilities",
          "Create at least 2 small sample projects",
          "Write a short story behind each project",
          "Keep portfolio link easy to share",
          "Update portfolio once per month",
          "Include results or impact where possible",
          "Ask 1 person to review portfolio clarity",
        ],
        [
          "List 10 people in or near your target field",
          "Reach out to 1 person per week",
          "Schedule short informational chats",
          "Prepare 3–4 good questions per chat",
          "Follow up with a thank-you message",
          "Update contacts on your progress monthly",
          "Offer help or value when you can",
          "Log key insights and names in one place",
        ],
        [
          "Set a weekly target for applications or outreach",
          "Tailor resume to each role type",
          "Write one strong reusable cover letter skeleton",
          "Track all applications in a simple table",
          "Follow up 7–10 days after applying",
          "Practice short answers to common questions",
          "Keep a library of your best interview stories",
          "Review and adjust strategy every 2–3 weeks",
        ],
        [
          "Calculate minimum monthly expenses",
          "Set a target ‘career change’ savings amount",
          "Automate a small weekly transfer to savings",
          "Reduce 1–2 non-essential expenses",
          "Plan how to handle a gap between jobs",
          "Track savings progress each week",
          "Avoid big new financial commitments",
          "Update plan with partner/family if relevant",
        ],
        [
          "Write down fears about changing careers",
          "Challenge each fear with one counter-thought",
          "Visualize a day in your new role",
          "Celebrate small steps (not just offers)",
          "Limit comparison with others’ timelines",
          "Journal after tough rejections",
          "List 5 ways current you is already capable",
          "Re-read your why when discouraged",
        ],
        [
          "Block weekly time for career work",
          "Discuss schedule and support with family",
          "Limit overtime in current job if possible",
          "Keep 1–2 evenings free for rest",
          "Plan how to handle commute or location shifts",
          "Organize key documents in a shared folder",
          "Plan childcare/house tasks if they’ll change",
          "Review logistics monthly and adjust",
        ],
      ]),
    },
    {
      id: "sidebiz",
      name: "Build a Side Business",
      description: "Launch and validate a small, profitable side project.",
      goal: "Launch and validate a profitable side business earning $X/month by [date].",
      pillars: [
        "Idea & Customer",
        "Offer & Pricing",
        "Product / Service Delivery",
        "Marketing Experiments",
        "Sales & Conversations",
        "Operations & Systems",
        "Money & Metrics",
        "Energy & Boundaries",
      ],
      tasks: makeTasks([
        [
          "Write a 1-sentence description of your idea",
          "Define your ‘perfect customer’ on one page",
          "List the main problem you solve for them",
          "Talk to 1 potential customer each week",
          "Note exact phrases customers use",
          "Identify 3 existing competitors",
          "Write why someone might choose you instead",
          "Refine idea after every 3 conversations",
        ],
        [
          "Draft 1 simple core offer",
          "List what’s included and what’s not",
          "Choose a starting price (even if low)",
          "Define a clear outcome for the customer",
          "Create a 1-page ‘offer sheet’",
          "Ask 1–2 people if the offer feels clear",
          "Adjust price after first few sales",
          "Set an ‘intro offer’ for first 3–5 clients",
        ],
        [
          "Decide the exact steps to deliver your service",
          "Create a simple checklist for delivery",
          "Prepare templates (emails, docs, etc.)",
          "Test your process with a friend or free client",
          "Time how long delivery actually takes",
          "Refine process to save 10–20% time",
          "Collect feedback after each delivery",
          "Add improvements to the checklist monthly",
        ],
        [
          "Pick 1 main channel (IG, email, etc.)",
          "Post value content 2–3x per week",
          "Share before/after or case-study style posts",
          "Track which posts get messages or replies",
          "Run 1 micro-experiment every 2 weeks",
          "Double down on what works, drop what doesn’t",
          "Test 1 simple lead magnet or free resource",
          "Measure leads per channel monthly",
        ],
        [
          "Reach out to 1 warm contact weekly",
          "Practice a short, clear explanation of offer",
          "Invite people to short ‘fit calls’",
          "Prepare 3–4 key questions for calls",
          "Practice handling 2–3 common objections",
          "Always suggest a next step at end of calls",
          "Follow up 1–2 times after calls",
          "Log every sales conversation in a sheet",
        ],
        [
          "Choose simple tools (GDrive, Notion, etc.)",
          "Create 1 central folder for all biz docs",
          "Set up repeatable weekly admin checklist",
          "Block 30–60 minutes weekly for admin",
          "Create basic onboarding steps for clients",
          "Save email templates for common replies",
          "Document 1 small process every week",
          "Keep passwords and logins organized",
        ],
        [
          "Track revenue and expenses weekly",
          "Set a simple monthly revenue goal",
          "Know your minimum profit per month",
          "Separate business money from personal",
          "Record how many hours you work weekly",
          "Calculate rough hourly rate monthly",
          "Identify highest ROI activities",
          "Adjust goals every 1–2 months",
        ],
        [
          "Limit side-business work to fixed hours",
          "Protect at least 1 full rest day weekly",
          "Communicate boundaries to family/housemates",
          "Set a nightly ‘shut-down’ time",
          "Watch for signs of burnout or resentment",
          "Celebrate small wins every week",
          "Plan time with friends/family first",
          "Re-evaluate whether the business still fits",
        ],
      ]),
    },
    {
      id: "wellbeing",
      name: "Mental Health & Well-Being",
      description: "Daily practices for calmer, steadier energy.",
      goal: "Build a sustainable mental health routine by [date].",
      pillars: [
        "Sleep & Rest",
        "Movement",
        "Food & Hydration",
        "Mind & Emotions",
        "Relationships",
        "Environment",
        "Work & Stress",
        "Joy & Play",
      ],
      tasks: makeTasks([
        [
          "Aim for a consistent sleep/wake time",
          "Create a simple wind-down routine",
          "Avoid screens 30 minutes before bed",
          "Keep bedroom as dark and cool as possible",
          "Limit caffeine later in the day",
          "Short daytime naps when overtired",
          "Notice patterns between sleep and mood",
          "Talk to a professional if sleep stays poor",
        ],
        [
          "Move your body at least 10–20 minutes daily",
          "Take a short walk after meals when possible",
          "Stretch tight areas once a day",
          "Try one fun movement you enjoy weekly",
          "Use stairs or extra walking when you can",
          "Check in with your body at midday",
          "Track movement in a simple log",
          "Rest when injured or exhausted",
        ],
        [
          "Drink a glass of water after waking",
          "Keep water nearby during the day",
          "Aim for balanced meals (carbs, protein, fat)",
          "Notice which foods crash your energy",
          "Plan 1–2 easy backup meals for busy days",
          "Eat slowly when you can",
          "Limit skipping meals multiple days in a row",
          "Talk to a pro if you struggle with food",
        ],
        [
          "Check in: ‘What am I feeling?’ once a day",
          "Name emotions without judging them",
          "Do 5 slow breaths when overwhelmed",
          "Journal for 5–10 minutes a few times per week",
          "Limit doomscrolling and news intake",
          "Notice unhelpful thought loops kindly",
          "Use grounding tools (5 things you can see, etc.)",
          "Consider therapy or support group if needed",
        ],
        [
          "Send 1 small message to someone you care about",
          "Schedule regular time with close people",
          "Share honestly when you’re struggling",
          "Listen fully at least once a day",
          "Set gentle boundaries when drained",
          "Spend less time with consistently toxic people",
          "Thank someone each week for something specific",
          "Ask for help at least once a month",
        ],
        [
          "Tidy one small area daily (5 minutes)",
          "Keep a ‘good enough’ standard, not perfect",
          "Let in natural light when possible",
          "Add one comforting item (plant, photo, etc.)",
          "Reduce visual clutter in sleep area",
          "Create a tiny ‘calm corner’ if possible",
          "Declutter 1 item or file per day",
          "Adjust environment to support your routines",
        ],
        [
          "List your top 3 stress triggers",
          "Notice stress signals in your body",
          "Take short breaks between tasks",
          "Use a simple to-do list for each day",
          "Protect at least one non-work time block",
          "Communicate capacity limits when overbooked",
          "Reflect weekly on what drained you",
          "Change one small thing about workload if you can",
        ],
        [
          "List 10 small things that bring you joy",
          "Schedule 1 ‘play’ moment daily (5–10 mins)",
          "Give yourself permission to do something silly",
          "Revisit an old hobby once a week",
          "Plan one small thing to look forward to",
          "Spend time outside when you can",
          "Notice moments of contentment during the day",
          "Capture one ‘good’ moment in a note or photo",
        ],
      ]),
    },
  ];
  